### ISSUE TITLE
Sendgrid Email not working

### ISSUE THREAD

**Issue by StanlyLife** [StanlyLife/Certify#2]
API Key storage implementation

**Comment by CreedsCode** [comment]
Still open? Or already done local?

**Comment by StanlyLife** [comment]
Still open. I dont know where to store and how to retrieve the secrets (api key).

Thanks for reaching out! Do you have a solution?

Sent from my iPhone

On 19 Apr 2020, at 21:28, CreedsCode <notifications@github.com> wrote:

﻿

Still open? Or already done local?

**Comment by CreedsCode** [comment]
I just created my approach for it, as a draft. #4 
I explained it there. I hope it's answered your question.
If you have still questions I hope that I can answer them, because I am not really long working with asp.Net.

**Comment by StanlyLife** [comment]
Thank you, i will take a look at it! from my understanding appsettings is not encrypted and it is suggested to use its own secret storage. however as this is only a "learning project" I will se if i can implement your fix, thank you very much!

**Comment by StanlyLife** [comment]
Again thanks for the help! May i ask how you found this repo? Also would you like to keep working on this project? @CreedsCode

**Comment by CreedsCode** [comment]
you're welcome, I just looked around, for some issues, w. help wanted tagged on them and where I knew that I can help. 
I can turn notifications on for the issues.
If you like you can add me on Discord, if you use it => CreedsCode#4930 too have a direct way to communicate. 
In addition to the secret storage, As I understood that it is for the local dev setup. But in production should be a thing to store it in a json, or pass it as an evn-var.
